<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
$images = $block->getGalleryImages();
if(count($images) > 0)
{
	$mainImage = $images->getFirstItem();
	foreach($images as $image)
	{
		if($block->isMainImage($image))
		{
			$mainImage = $image;
			break;
		}
	}
?>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder" id="gallery_<?php $block->getProduct()->getId(); ?>" >
	<div class="product-slider-wrapper">
		<div class="main-img-quickview">
			<a href="<?php echo $mainImage->getData('large_image_url'); ?>" class="cloud-zoom" rel="transparentImage: 'data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==', useWrapper: false, showTitle: false, zoomWidth:'100', adjustY:0, adjustX:0">
				<img src="<?php echo $mainImage->getData('medium_image_url'); ?>">
			</a>
		</div>
	</div>
	<div class="row">
		<ul class="bxslider owl">
		<?php foreach ($images as $_image) { ?>
			<li class="small_image <?php if($block->isMainImage($_image)) echo "active"; ?>"><img src="<?php echo $_image->getData('small_image_url'); ?>" data-href="<?php echo $_image->getData('large_image_url'); ?>" data-thumb-image="<?php echo $_image->getData('medium_image_url'); ?>"></li>
		<?php } ?>
		</ul>
	</div>
</div>
<?php } ?>
<script>
require([
		'jquery',
		'mage/mage',
		'quickview/cloudzoom',
		'rokanthemes/owl'
	], function ($) {
	jQuery(document).ready(function() {
		jQuery('#gallery_<?php $block->getProduct()->getId(); ?> .cloud-zoom, #gallery_<?php $block->getProduct()->getId(); ?> .cloud-zoom-gallery').CloudZoom({
			adjustX: 0,
			adjustY: 0
		});
		$(document).on('click','#gallery_<?php $block->getProduct()->getId(); ?> .owl .small_image', function(){  
			$('#gallery_<?php $block->getProduct()->getId(); ?> .owl .small_image').removeClass('active');
			$(this).addClass('active');
			var currentImg = $(this).children('img');
			jQuery('#gallery_<?php $block->getProduct()->getId(); ?> a.cloud-zoom').attr('href', currentImg.attr('data-href'));
			jQuery('#gallery_<?php $block->getProduct()->getId(); ?> a.cloud-zoom img').attr('src', currentImg.attr('data-thumb-image'));
			$('.cloud-zoom, .cloud-zoom-gallery').CloudZoom();
		});
		$('#gallery_<?php $block->getProduct()->getId(); ?> .owl').owlCarousel({
			autoPlay : false,
			items : 4,
			itemsDesktop : [1199,4],
			itemsDesktopSmall : [980,4],
			itemsTablet: [768,4],
			itemsMobile : [479,3],
			slideSpeed : 500,
			paginationSpeed : 500,
			rewindSpeed : 500,
			navigation : true,
			stopOnHover : true,
			pagination :false,
			scrollPerPage:true,
		});
	});
});
</script>
