<div id="back-top" class="hidden-xs"><i class="fa fa-angle-double-up"></i></div>

<div class="row pl-banner-newsletter">
    <div class="col-sm-12">
        <div class="row">
	    <!--
            <div class="col-sm-3"><img class="img-responsive pl-img-ipad" src="/media/ipad.png" /></div>
            <div class="col-sm-1">
                <h2>Rimani in contatto</h2>
            </div>
            <div class="col-sm-8"><form action="/hoop_contacts/index/index" method="post"><input name="from" type="hidden" value="mailchimpform" />
                    <p>Iscriviti alla nostra newsletter per essere sempre aggiornato sulle novit&agrave; di prodotto, le offerte e le promozioni in corso.</p>
                    Inserisci la tua email &nbsp;<input name="email" type="email" data-validate="{required:true, 'validate-email':true}" /> &nbsp;&nbsp;&nbsp;
		    <input type="submit" value="Iscriviti" /> <br />
                    <div class="col-sm-12 text-left field required" style="margin-bottom: 15px;">
                        <input id="privacy" class="check-right" name="privacy" data-validate="{required:true}" required="true" type="checkbox"> Confermo di aver letto l'informativa al trattamento. Per l'informativa completa clicca <a href="/it/privacy" target="_blank">qui</a><span class="pl-asterisk">*</span>
                    </div>


                        <div class="col-sm-12 field text-left newsletter" style="margin-bottom: 15px;">
                            <input style="display: inline-block;" type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ echo __("Autorizzo al trattamento del mio nome ed indirizzo mail per l'iscrizione alla newsletter") ?>" value="1" id="is_subscribed" class="checkbox" data-validate="{required:true}" required="true">
                            <?php /* @escapeNotVerified */ echo __("Autorizzo al trattamento del mio nome ed indirizzo mail per l'iscrizione alla newsletter") ?><span class="pl-asterisk">*</span>
                        </div>
                        <?php /* Extensions placeholder */ ?>
                        <?php echo $block->getChildHtml('customer.form.register.newsletter')?>

                </form></div>
	    -->
        </div>
    </div>
</div>


<div class="footer-container">
	<div class="footer-static-container">
		<div class="container">
			<?php echo $this->getChildHtml("footer_static"); ?>
		</div>
	</div>
	<div class="footer-bottom">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-xs-12">
					<?php echo $this->getChildHtml("copyright"); ?>
				</div>
				<div class="col-md-6 col-xs-12">
					<?php echo $this->getChildHtml("social_block"); ?>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	window.onload = function () {
		document.body.className += " preloaded";
	}
</script>
