<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue): ?>
<div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
    <?php if ($_attributeLabel != 'none' && $_attributeLabel != 'nessuno'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?></strong><?php endif; ?>
    <div class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>>
    <?php /* @escapeNotVerified */ echo str_replace("&nbsp;"," ",$_attributeValue); ?></div>
</div>
<?php endif; ?>

<?php // giorg 20171009 - la schifezza, se metto il mio tab custom il tema lo sposta in alto -.- ?>
<?php if ($_attributeLabel == 'SKU'): ?>
<script type="text/javascript">
    require([
        'jquery',
        'mage/mage'
    ], function ($) {
        'use strict';
        $( document ).ready(function() {
            if ($('.product.info.detailed').length) {
               $('.product.info.detailed').appendTo($('.product.info.detailed').parent());
               $('.data.item.title:eq(0)').appendTo($('.data.item.title:eq(0)').parent());
               $('.data.item.content:eq(0)').appendTo($('.data.item.content:eq(0)').parent());
            }
        });
    });
</script>
<?php endif; ?>