<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

// giorg 20170726 - mi serve url media per img ombra prima dei correlati
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager= $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info','getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <?php if ($name == 'valori_nutrizionali.tab'): ?>

                    <?php  // giorg 20171010 - tab custom
                    $p = $block->getProduct();
                    if($p->getData('valori_nutrizionali')):
                        ?>
                        <div class="data item title"
                             aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                             data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                            <a class="data switch pl-fontlato"
                               tabindex="-1"
                               data-toggle="switch"
                               href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                               id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                                <?php if ($label == 'Dettagli') $label = 'Descrizione'; ?>
                                <?php /* @escapeNotVerified */ echo $label; ?>
                            </a>
                        </div>
                        <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                            <?php /* @escapeNotVerified */ echo $html; ?>
                        </div>
                    <?php endif ?>
                <?php else: ?>
                    <div class="data item title"
                         aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                         data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                        <a class="data switch pl-fontlato"
                           tabindex="-1"
                           data-toggle="switch"
                           href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                           id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                            <?php if ($label == 'Dettagli') $label = 'Descrizione'; ?>
                            <?php /* @escapeNotVerified */ echo $label; ?>
                        </a>
                    </div>
                    <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                        <?php /* @escapeNotVerified */ echo $html; ?>
                    </div>
                <?php endif ?>

            <?php endforeach;?>
        </div>
        <img src="<?php echo $mediaUrl ?>shadow.png" class="img-responsive" />
    </div>
<?php endif; ?>