<div class="header-container">
	<div class="header">
		<div class="row">
			<div class="col-md-2 col-sm-2 col-xs-6 col-logo">
				<?php echo $this->getChildHtml("logo"); ?>
			</div>
			<div class="col-md-10 col-sm-10 col-xs-6 col-menu-control pull-right">
				<?php echo $this->getChildHtml("minicart");?>
				<div class="header-top-setting pull-right">
					<i class="fa fa-bars"> </i>
					<div class="setting-container">
						<h3><?php echo __('My Account') ?></h3>
						<?php echo $this->getChildHtml("top_link"); ?>
						<h3><?php echo __('Language') ?></h3>
						<?php echo $this->getChildHtml("store_language"); ?>
						<h3><?php echo __('Currency') ?></h3>
						<?php echo $this->getChildHtml("currency"); ?>
					</div>
				</div>
				<?php echo $this->getChildHtml("top.search"); ?>
				<?php echo $this->getChildHtml("top.navigation.sections"); ?>
			</div>
		</div>
	</div>
</div>

