<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager= $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>
<form class="form contact pl-contacts"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>

        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <img src="<?php echo $mediaUrl ?>contact_banner.jpg" class="img-responsive" />
                </div>
                <div class="col-sm-9">
                    <fieldset class="fieldset">
                    <h3><?php echo __('Contact us'); ?></h3>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="field firstname required">
                                <label class="label" for="firstname"><span><?php /* @escapeNotVerified */ echo __('Firstname') ?></span><span class="pl-asterisk">*</span></label>
                                <div class="control">
                                    <input name="firstname" id="firstname" title="<?php /* @escapeNotVerified */ echo __('Firstname') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="field lastname required">
                                <label class="label" for="lastname"><span><?php /* @escapeNotVerified */ echo __('Lastname') ?></span><span class="pl-asterisk">*</span></label>
                                <div class="control">
                                    <input name="lastname" id="lastname" title="<?php /* @escapeNotVerified */ echo __('Lastname') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="field email required">
                                <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('E-mail') ?></span><span class="pl-asterisk">*</span></label>
                                <div class="control">
                                    <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('E-mail') ?>" value="" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="field company required">
                                <label class="label" for="company"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
                                <div class="control">
                                    <input name="company" id="company" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" value="" class="input-text" type="text" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="field telephone">
                                <label class="label" for="phone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
                                <div class="control">
                                    <input name="phone" id="phone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="field message required">
                                <label class="label" for="message"><span><?php /* @escapeNotVerified */ echo __('Message') ?></span><span class="pl-asterisk">*</span></label>
                                <div class="control">
                                    <textarea name="message" id="message" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="6" data-validate="{required:true}"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row auth-privacy">
                        <div class="col-sm-12 text-left">
                            <input type="checkbox" id="privacy" class="check-right" name="privacy" data-validate="{required:true}" /> <?php echo  __('I authorise the processing of my data in order to follow up my request. Personal data will be processed as described in this '); echo '<a href="/' . $storeManager->getStore()->getCode() . '/privacy" target="_blank">' . __('policy statement') . '</a>' ?><span class="pl-asterisk">*</span>
                        </div>
                        <div class="col-sm-12">
                            <input type="checkbox" id="newsletter" class="check-right" name="newsletter" /> <?php echo  __('I consent to the processing of my personal data for marketing purposes as described in this '); echo '<a href="/' . $storeManager->getStore()->getCode() . '/privacy" target="_blank">' . __('policy statement') . '</a>' ?>
                        </div>

                        <div class="actions-toolbar">
                            <div class="primary">
                                <input type="hidden" name="hideit" id="hideit" value="" />
                                <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary pl-contact-submit">
                                    <span><?php /* @escapeNotVerified */ echo __('Send') ?></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <?php echo $block->getChildHtml('form.additional.info'); ?>
                </fieldset>

            </div>
        </div>
</form>
